package no.behn.typingStomp;

import org.springframework.stereotype.Service;
import java.util.Random;

@Service
public class TextService {
    
    // Temporary texts, texts are generated by chatGPT
    private static final Text[] texts = {
        // Text 1: Maneter
        new Text("Maneter er marine dyr som tilhører gruppen nesledyr og er kjent for sine geleaktige kropper og tentakler. De bruker nesleceller for å lamme byttet sitt og forsvare seg mot fiender. Maneter finnes i alle verdenshav og kan variere i størrelse fra noen få millimeter til flere meter i diameter.", 47), // 47 words

        // Text 2: Fjell
        new Text("Fjell er massive landformer som stiger høyt over det omkringliggende landskapet. De dannes hovedsakelig gjennom tektoniske bevegelser og vulkansk aktivitet. Mange fjell er hjem til unike økosystemer og sjeldne arter.", 34), // 34 words

        // Text 3: Skoger
        new Text("Skoger dekker omtrent en tredjedel av jordens landareal og spiller en viktig rolle i klodens økosystem. De er hjem til millioner av arter, inkludert mange truede dyre- og plantearter. Skoger bidrar også til å regulere klimaet og produsere oksygen.", 40), // 40 words

        // Text 4: Innsjøer
        new Text("Innsjøer er store vannmasser som ligger innlandet og kan være enten ferskvann eller saltvann. De fungerer som viktige ressurser for drikkevann, rekreasjon og habitat for dyreliv. Innsjøer kan også påvirke lokalt klima og værmønstre.", 36), // 36 words

        // Text 5: Ørkener
        new Text("Ørkener er tørre områder som mottar svært lite nedbør og har ekstremt varierende temperaturer. Til tross for det tøffe klimaet, er ørkener hjem til tilpassede planter og dyr. Mange ørkener har unike landskap, som sanddyner og klippeformasjoner.", 39), // 39 words

        // Text 6: Elver
        new Text("Elver er naturlige vannveier som renner fra høyere til lavere områder og ofte munner ut i havet. De spiller en viktig rolle i økosystemer ved å transportere næringsstoffer og gi habitat for mange arter. Elver er også viktige for menneskelig aktivitet, inkludert landbruk og transport.", 43), // 43 words

        // Text 7: Korallrev
        new Text("Korallrev er undervannsstrukturer laget av små marine organismer kalt korallpolyper. Disse revene gir habitat for et stort mangfold av marine arter og beskytter kystlinjer mot erosjon. Korallrev er svært sårbare for klimaendringer og forurensning.", 35), // 35 words

        // Text 8: Tundra
        new Text("Tundraen er en kald og treløs region som finnes i polare områder og på høyfjellsplatåer. Jordsmonnet i tundraen er ofte frosset, noe som begrenser plantevekst. Til tross for de tøffe forholdene, støtter tundraen en rekke spesialiserte arter.", 35), // 35 words

        // Text 9: Savanner
        new Text("Savanner er store gressletter med spredte trær, funnet hovedsakelig i tropiske og subtropiske områder. De har sesongbaserte regntider og tørkeperioder, som påvirker dyre- og plantelivet. Savanner er kjent for sitt rike dyreliv, inkludert mange store pattedyr.", 37), // 37 words

        // Text 10: Regnskoger
        new Text("Regnskoger er tette skoger som mottar høy nedbørsmengde og er kjent for sitt enorme biologiske mangfold. De spiller en avgjørende rolle i å opprettholde globale klima- og værmønstre. Regnskoger trues imidlertid av avskoging og klimaendringer.", 35) // 35 words
    };
    
    public Text getText() {
        // TODO bytt ut med faktisk henting av tekst fra en database etterhvert
        Random random = new Random();
        int index = random.nextInt(texts.length);
        return texts[index];
    }
}



